### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by benbro** [LibVNC/x11vnc#10]
Ubuntu has a very old version of x11vnc.
Maybe if there will be a newer x11vnc stable release, it'll be easier for them to upgrade the package.
http://packages.ubuntu.com/vivid/x11vnc

**Comment by bk138** [comment]
Hi, there are still a few issues for the 0.9.14 release. Care to help? ;-)

**Comment by benbro** [comment]
I only see two more issues.
And I find it hard to believe that the project today is not more stable than few years ago :)

**Comment by bk138** [comment]
Yeah maybe time for a new release. But anyways, co workers welcome.

**Comment by benbro** [comment]
Is there a chance for a release?
None of the pending issues in the 0.9.14 milestone seems like a blocker.
Ubuntu 16.04 will be freeze soon and we'll be stuck with an old release for additional 2 years.

**Comment by bk138** [comment]
Care to help?

**Comment by bk138** [comment]
Here you go https://github.com/LibVNC/x11vnc/releases/tag/0.9.14

**Comment by benbro** [comment]
Thank you!

Do you know how can we let the Ubuntu maintainers know about the new release?

**Comment by bk138** [comment]
With Debian, it's filing a bug report saysing "hey, there's a new release". Ubuntu might be similar I guess...

**Comment by benbro** [comment]
I sent a message to both debian and ubuntu.
I think that ubuntu uses the debian package.
