### ISSUE TITLE
x11vnc and Gemini Lake

### ISSUE THREAD

**Issue by DerPit** [LibVNC/x11vnc#100]
Hi,

I'm having issues with remote access to an ASUS PN40 (Celeron N4000, UHD Graphics 600 (Geminilake 2x6)) using x11vnc.  Both the PN40 and my laptop for accessing it are running openSUSE Tumbleweed.  Xorg is 1.20.4, Mesa is 19.0.3, x11vnc is 0.9.16. Viewer is tigervnc 1.9.0.
The computers are connected via copper 1 Gbit network.

When using the modesetting driver (which is the default), the screen updates are extremely intermittent, sometimes with a lag of more than a second.  Moving a window around is close to impossible. On the PN40 I can see that the CPU usage of the X server goes up to 100%

If instead I run the intel driver (xf86-video-intel-2.99.917+git8674.25c9a2fcc) access is smooth and updates are instantaneous.  CPU load of the X server is (way) below 10%.

When working directly on the PN40 with the connected monitor both drivers run without issues. Based on a simple glxgears run with disabled vsync the modesetting driver is even a bit faster than the intel one.

If I use the same laptop to connect to another system running modesetting on older intel graphics I do not see this slowdown.  It is however also an older OS:
i5-5200U with HD5500, OS Leap 42.3, Xorg 7.6, Mesa 17.0.5, x11vnc 0.9.13.

I had opened a ticket on the openSUSE bugzilla (https://bugzilla.opensuse.org/show_bug.cgi?id=1135237), there's some more info about tests I ran.  We had concluded it might be worth asking here if you have some ideas how to track down the issue.

**Comment by bk138** [comment]
It might have to do with GLAMOR. Try disabling that on the modesetting driver and/or try to play around with x11vnc's multitude of screen/opengl options...

**Comment by bk138** [comment]
Tentatively closing, please re-open if the issue persists.

**Comment by bk138** [comment]
Related to #58 ?
