### ISSUE TITLE
Is tightvnc decoder supported?

### ISSUE THREAD

**Issue by NobodyXu** [LibVNC/x11vnc#101]
I am planning on using [VirtScreen][3], a software depends on this, to use ipad as the second screen for my linux.

However, I heard that this can be very slow compared to other solution like [Duet Display][2], and according to @kbumsik kbumsik/VirtScreen#31, it is primary due to the lack of compression.

I found that [tightvnc][1] has [tight decoding][4] whose [performance][6] seems to be quite impressive compared to other way of compression. It also provides [remote-ripple on ipad][5], which is exactly what I need.

My question is, is [tightvnc][1] and its [encoding][4] supported on `x11vnc`?

[1]: https://www.tightvnc.com/
[2]: https://www.duetdisplay.com/
[3]: https://github.com/kbumsik/VirtScreen
[4]: https://www.tightvnc.com/decoder.php
[5]: https://itunes.apple.com/ru/app/remote-ripple/id1071186450?l=en&mt=8
[6]: https://www.tightvnc.com/archive/compare.html

**Comment by bk138** [comment]
yes, it is. 

Am 20. Mai 2019 06:36:17 MESZ schrieb NobodyXu <notifications@github.com>:
>I am planning on using [VirtScreen][3], a software depends on this, to
>use ipad as the second screen for my linux.
>
>However, I heard that this can be very slow compared to other solution
>like [Duet Display][2], and according to kbumsik/VirtScreen#31, it is
>primary due to the lack of compression.
>
>I found that [tightvnc][1] has [tight decoding][4] whose
>[performance][6] seems to be quite impressive compared to other way of
>compression. It also provides [remote-ripple on ipad][5], which is
>exactly what I need.
>
>My question is, is [tightvnc][1] and its [encoding][4] supported on
>`x11vnc`?
>
>[1]: https://www.tightvnc.com/
>[2]: https://www.duetdisplay.com/
>[3]: https://github.com/kbumsik/VirtScreen
>[4]: https://www.tightvnc.com/decoder.php
>[5]:
>https://itunes.apple.com/ru/app/remote-ripple/id1071186450?l=en&mt=8
>[6]: https://www.tightvnc.com/archive/compare.html
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibVNC/x11vnc/issues/101

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by NobodyXu** [comment]
@bk138 Thank you so much for replying!

So all I have to do is have a `tightvnc` client to connect to `x11vnc` on the server and the tight encoder will automatically be used, right?

**Comment by bk138** [comment]
Very probably indeed, yes :-)

**Comment by NobodyXu** [comment]
Thank you so much!
