### ISSUE TITLE
TCP6 port is different from the TCP port as instructed by -rfbport

### ISSUE THREAD

**Issue by kewlfft** [LibVNC/x11vnc#103]
To reproduce the issue, run:
`$ x11vnc -display :0 -rfbport 5908`
it returns
~~~
08/06/2019 Listening for VNC connections on TCP port 5909
08/06/2019 Listening for VNC connections on TCP6 port 5900
~~~
now run the command:
`$ x11vnc -display :0 -rfbport 5908 -rfbportv6 5908`
~~~
08/06/2019 Listening for VNC connections on TCP port 5909
08/06/2019 Listening for VNC connections on TCP6 port 5909
~~~
The expected behavior is not to need to use `-rfbport6` to align the 2 ports listening.

**Comment by bk138** [comment]
Well, that _is_ the expected behaviour, at least by some people, because it has been like this for a while.

**Comment by tomty89** [comment]
@bk138 I don't know if it's some more recent "been-a-while" behaviors, but now `-rfbport $port` makes an instance binds to `$port` for both v4 and v6, but also `5900` for (only) v6. To suppress that, `-rfbportv6 $port` needs to be specified. Yet, if only `-rfbportv6 $port` is used, it will be a no-op (i.e. binds to only `5900` for both v4 and v6). Do these behaviors *really* make sense / make *anyone* happy...?

**Comment by tacaswell** [comment]
I agree with @tomty89 , binding 2 ip6 ports (5900 and $port) when specifying `-rbfport $port` is not something I think anybody wants.

-----

This behavior (along with xrdp trying ip6 localhost first and running multiple x11vnc servers on ports {5900, 5901, 5902, ...} for individual screens) took us a better part of a day to debug.

**Comment by Neustradamus** [comment]
There is ticket done by @luke-jr here:
- https://github.com/LibVNC/x11vnc/issues/213
