### ISSUE TITLE
Handle double buffered framebuffer devices

### ISSUE THREAD

**Issue by hcw70** [LibVNC/x11vnc#106]
Dear maintainers of X11VNC.

We are using x11vnc to publish the linux framebuffer sucessfully (including server rotation) to vnc clients.

However, we are using application side double buffering as show on

https://pandorawiki.org/Kernel_interface#double_buffering

with a double-height display and switching to the other half upon each redraw.

This however limits the usage of x11vnc since that only seems to display the upper half display, which lets the client being stuck at every second frame. If the application does not have anything to paint / update, the display stays on the wrong frame.

Is there a possibility to add a call like:

`ioctl( mFbFd, FBIOGET_VSCREENINFO, &mFbVinfo );
`
 
to query the framebuffer screen config and respect the
` mFbVinfo.yoffset
`

y offset in the calculation?

I had a look at the sources already but am not sure about the proper location to add something this (since x11vnc handles a lot scenarios where the data can come from).

Kind regards

Hauke

**Comment by hcw70** [comment]
Are there any hints on this?

**Comment by bk138** [comment]
Dear Hauke,
I haven't dug into the code for a very long time, so I propose you simply make a draft PR and we find out together if the location fits. Maybe you hit the right spot on the first try :-)

`linuxfb.c` might be something although it only seems to handle input. 

It would help to know your exact command line arguments for x11vnc.

**Comment by hcw70** [comment]
Hi Christian.
Thanks for your reaction.

The command line is:

`/usr/bin/x11vnc -viewonly -rawfb file:/dev/fb0@800x480x16 
`

The reason i did not change this myself and make a PR is that the code looks too "old aged" for me. It is C-only with a lot of pointers and stuff without any comments, so really hard to read (and i am used to read C++ nowadays)....

So a hint on this would be great....

**Comment by bk138** [comment]
Mh maybe there https://github.com/LibVNC/x11vnc/blob/cb88cb27825e7ced4f9f7ea3939c1ded0edfea3c/src/screen.c#L1639 ? 

Please note that I didn't write that code...

**Comment by hcw70** [comment]
Hi Christian. 

Thanks for the hint, i will start my further investigations there!

Kind regards

Hauke

**Comment by bschaef14** [comment]
So I just started looking into this issue (FYI new to x11vnc source but some experience with double buffered devices..).

Please let me know if any of this is wrong.

Right now, the rfb (remote frame buffer device) geometry is tied to what's determined through `console_guess` or what's specified on the command line in -rawfb string. `initialize_raw_fb` only mmaps what is specified by the -rawfb string.. so I think an optional param needs to be added to rawfb string and should specify the virtual size of the fb.

NOTE: I tried `rawfb map:/dev/fb0@800x960x16 -clip 800x480`, to mmap the full virtual frame buffer but only dispaly half over vnc, and this didn't work. VNC frame size matched that of rawfb.

I haven't gone too much further yet.. but the `XImage raw_fb_image.data` should then be the size of the entire double buffered fb I think. `scan.h` needs to be double buffer aware to compare the correct portion of `raw_fb_image.data` to what was last sent to the client...

Looking for feedback if this seems the correct route, specifically right now on what options need to exist for a user to specify the device is double buffered: current rawfb string is this: `mode:file@WxHxB:R/G/B+O-BPL`; how should this be changed to include `xresvirtualxyresvirtual`
