### ISSUE TITLE
wss not working

### ISSUE THREAD

**Issue by laoshaw** [LibVNC/x11vnc#108]
newest libvncserver and x11vnc, also tried ubuntu 18.04 64bit default libvncserver with newest x11vnc. use novnc to connect without websockify, running under nginx

1. http works perfectly, http was change to ws://, no need to do proxy_pass at all.
2. https works fine, novnc login page showed up correctly with https, however, when login via novnc it can never get wss://mysite.com:5900 to work, the error message is:

websock.js:184 WebSocket connection to 'wss://mysite.com:5900/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET

it seems x11vnc can not upgrade https:443 to wss:5900 internally, anyone tested this before?

Thanks for your help

**Comment by laoshaw** [comment]
I can use ws client to connect to http://mysite.com:5900 successfully, however after I enabled https, while I can visit all the webpages, I can never connect to https://mysite.com:5900, same options are used with x11vnc, do i need some flag to enable x11vnc's ssl features?

**Comment by mikewyszinski** [comment]
hi i'm looking at using novnc to connect to x11vnc over the internet, so setting up my server to use secure websockets is a must.... Were you able to get novnc to connect to x11vnc via wss://mysite.com:5900 or is there a bug?
