### ISSUE TITLE
Duplicate mouse cursor on server with -multiptr

### ISSUE THREAD

**Issue by Bonnee** [LibVNC/x11vnc#127]
**Describe the bug**
I am using x11vnc to extend my desktop monitor to my laptop's. I want to be able to see the mouse cursor from the laptop by using -multiptr but as soon as the client connects, a copy of the cursor appears on the server's monitor within a box. It changes shape together to the real cursor but it stays in the same location on the screen.

**To Reproduce**
1. Start server with `x11vnc -clip 1920x1080+0+540 -forever -multiptr`
2. Connect with a client

**Screenshots**

![2020-03-26-175037_5760x2160_scrot](https://user-images.githubusercontent.com/12095774/77673486-84a81780-6f8a-11ea-90da-ef7575a27229.png)
It doesn't show in the screenshot, but in the circled square I see the copy of the cursor

**Desktop:**
 - OS and version: Arch Linux
 - Xorg version used: 1.20.7 
 - Latest Nvidia drivers

**Comment by bk138** [comment]
Can you please describe what you expect? (The second cursor is intended as multiptr mode creates a cursor for each connected client. The rendering though looks flaky...)

**Comment by Bonnee** [comment]
Sorry I misunderstood what multiptr does, It's clearly doing what it's supposed to (except for the weird rendering).
The problem is that the cursor appears even if I connect to the server in view only mode, which is what I was doing, and it got me confused about a not moving mouse pointer. A workaround is not to connect in view only mode

**Comment by bk138** [comment]
Frei free to close then 🙂
