### ISSUE TITLE
Fails to build from source (GCC-10)

### ISSUE THREAD

**Issue by frikiluser** [LibVNC/x11vnc#128]
Hi,

As reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957965 , the code fails to build with GCC-10.

I've patched that way: https://salsa.debian.org/debian-remote-team/x11vnc/-/blob/master/debian/patches/0004-x11vnc.ftbfs-gcc10.patch

Please, consider applying upstream for coming releases.

**Comment by bk138** [comment]
Isn't this already fixed by a48b0b1cd887d7f3ae67f525d7d334bd2feffe60?

**Comment by frikiluser** [comment]
> Isn't this already fixed by [a48b0b1](https://github.com/LibVNC/x11vnc/commit/a48b0b1cd887d7f3ae67f525d7d334bd2feffe60)?

Yes, that's it!
So sorry

**Comment by bk138** [comment]
No problem!
