### ISSUE TITLE
TLS Handshake failed error w/ OpenSSL 1.1.x

### ISSUE THREAD

**Issue by vishnumotghare** [LibVNC/x11vnc#129]
I'm trying to connect x11vnc server through VncViewer (TigerVnc). I'm giving following command to start vnc server with -ssl option

$ x11vnc -ssl -rfbauth /home/root/.vnc/passwd

When I'm trying to connect the vnc server, I'm getting TLS handshake failed error.
Following is the vncserver log

07/05/2020 13:25:58 SSL: accept_openssl(OPENSSL_VNC)
07/05/2020 13:25:58 SSL: spawning helper process to handle: 172.21.33.47:64181
07/05/2020 13:25:58 SSL: helper for peerport 64181 is pid 629:
07/05/2020 13:25:58 connect_tcp: trying: 127.0.0.1 20000
07/05/2020 13:25:59 check_vnc_tls_mode: waited: 1.422183 / 1.40 input: (future) RFB Handshake
07/05/2020 13:26:00 check_vnc_tls_mode: version: 3.8
07/05/2020 13:26:00 check_vnc_tls_mode: reply: 19 (VeNCrypt)
07/05/2020 13:26:00 vencrypt: received 0.2 client version.
07/05/2020 13:26:00 vencrypt: client selected sub-type: 257 (rfbVencryptTlsNone)
07/05/2020 13:26:00 Using Anonymous Diffie-Hellman mode.
07/05/2020 13:26:00 WARNING: Anonymous Diffie-Hellman uses encryption but is
07/05/2020 13:26:00 WARNING: susceptible to a Man-In-The-Middle attack.
07/05/2020 13:26:00 loaded Diffie Hellman 1024 bits, 0.001s
07/05/2020 13:26:00 SSL: ssl_init[629]: 6/6 initialization timeout: 20 secs.
07/05/2020 13:26:01 SSL: ssl_helper[629]: SSL_accept() *FATAL: -1 SSL FAILED
07/05/2020 13:26:01 SSL: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher
07/05/2020 13:26:01 SSL: ssl_helper[629]: Proto: unknown
07/05/2020 13:26:01 SSL: accept_openssl: cookie from ssl_helper[629] FAILED. 0

This was working properly without error. Only change is openssl version, It changed from OpenSSL 1.0.2p 14 Aug 2018 to OpenSSL 1.1.1d 10 Sep 2019.

I checked that OpenSSL 1.1.1d support TLSv1.3 & TigerVNC supports TLSv1.2, Is the error because of version mismatch in SSL version?

**Comment by bk138** [comment]
Yeah, it might be that semantics have changed. Pls try with OpenSSL 1.0.x to test!

**Comment by vishnumotghare** [comment]
@bk138 , I'm able to connect with x11vnc server, I used  another client i.e ssvnc
```
15/05/2020 08:08:12 check_vnc_tls_mode: waited: 0.000059 / 1.40 input: SSL Handshake
15/05/2020 08:08:12 SSL: ssl_init[6772]: 6/6 initialization timeout: 20 secs.
15/05/2020 08:08:12 SSL: ssl_helper[6772]: SSL_accept() succeeded for: 172.26.218.112:52619
15/05/2020 08:08:12 SSL: ssl_helper[6772]: Cipher: TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 Proto: unknown
15/05/2020 08:08:12 SSL: ssl_helper[6772]: accepted client 172.26.218.112 x509 peer cert is null
15/05/2020 08:08:12 SSL: handshake with helper process[6772] succeeded.
15/05/2020 08:08:12 0 other clients
```
But problem is connection is very slow with ssvnc. The Handshake problem from TigerVnc may be due to client is not able match the ciphers supported by  servers. Is there any way to configure the x11vnc at run/compile time with specific cipher like "ADH-AES128-GCM-SHA256"?

Or is there any option to pass ciphers supported by  server from TigerVnc?

**Comment by vishnumotghare** [comment]
I asked same question in openssl forum [https://github.com/openssl/openssl/issues/11975](url) & I got  solution there. 

x11vnc server uses ADH based   ciphersuites which are not available in the default security level in 1.1.1,  This was not the case in 1.0.2
```
<snip>
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
	/* Security level must be set to 0 for unauthenticated suites. */
	SSL_CTX_set_security_level(ctx, 0);
#endif
	if (!SSL_CTX_set_cipher_list(ctx, "ADH:@STRENGTH")) {
		return 0;
	}
	if (!add_anon_dh()) {
		return 0;
	}
```
I lowered the ADH security level from"ADH:@STRENGTH to ADH:@SECLEVEL=0 & it worked

```
diff --git a/src/sslhelper.c b/src/sslhelper.c
index 1a3e747..77ba7b1 100644
--- a/src/sslhelper.c
+++ b/src/sslhelper.c
@@ -1596,7 +1596,7 @@ static int switch_to_anon_dh(void) {
        if (ssl_client_mode) {
                return 1;
        }
-       if (!SSL_CTX_set_cipher_list(ctx, "ADH:@STRENGTH")) {
+       if (!SSL_CTX_set_cipher_list(ctx, "ADH:@SECLEVEL=0")) {
                return 0;
        }
        if (!add_anon_dh()) {
```
Please let me know whether this can be the actual solution or workaround for this problem?

**Comment by bk138** [comment]
Sounds related to https://github.com/LibVNC/libvncserver/issues/347 

Feel free to provider a PR!

**Comment by puleglot** [comment]
But there was already fix for this issue:
https://github.com/LibVNC/x11vnc/commit/b9cf79fd3d61a7586fe6b24b3141e406cdf334eb
Or am I missing something?

**Comment by bk138** [comment]
Seems this wasn't enough: Watch the full story over at https://github.com/LibVNC/libvncserver/issues/347 :-)
