### ISSUE TITLE
not accepting Windows VNC viewer connections

### ISSUE THREAD

**Issue by br6** [LibVNC/x11vnc#135]
**Describe the bug**
Unable to connect from Windows 10/2019 vnc viewer (real, tight ultravnc)

**To Reproduce**
connect to the server, does not connect , the x11vnc.log in the server shows this
15/06/2020 23:11:10 Got connection from client 192.168.0.2
15/06/2020 23:11:10   0 other clients
15/06/2020 23:11:11 Normal socket connection
15/06/2020 23:11:11 Disabled X server key autorepeat.
15/06/2020 23:11:11   to force back on run: 'xset r on' (3 times)
15/06/2020 23:11:11 incr accepted_client=27 for 192.168.0.2:21728  sock=10
15/06/2020 23:11:11 Client Protocol Version 3.8
15/06/2020 23:11:11 Protocol version sent 3.8, using 3.8

**Expected Behavior**
Works perfectly fine on mac catalina, real vnc viewer on raspberrypi, ios and android, vnc on manjaro, ubuntu x64.

Manjarao ARM 64BIT Raspberry PI4. (20.06)
X11VNC version x11vnc version: 0.9.16
xdpyinfo -display :0 | grep version
version number:    11.0
X.Org version: 1.20.8

**Comment by br6** [comment]
22/06/2020 11:17:24 Got connection from client 192.168.0.2
22/06/2020 11:17:24   0 other clients
22/06/2020 11:17:25 Normal socket connection
22/06/2020 11:17:25 Disabled X server key autorepeat.
22/06/2020 11:17:25   to force back on run: 'xset r on' (3 times)
22/06/2020 11:17:25 incr accepted_client=11 for 192.168.0.2:23525  sock=10
22/06/2020 11:17:25 Client Protocol Version 3.8
22/06/2020 11:17:25 Protocol version sent 3.8, using 3.8

**Comment by br6** [comment]
ssh tunnel is working fine

**Comment by bk138** [comment]
Please make sure the firewall on the windows boxx is disabled.

**Comment by br6** [comment]
> Please make sure the firewall on the windows boxx is disabled.

I am investigating the firewall,  now I think its blocking VNC connections to server in question, the address I am using also happens to run pihole DNS server (docker) I can see event related vnc being filtered 5152 in windows. even after switching off firewall the connection is blocked/filtered.
 The Windows Filtering Platform has blocked a packet.

Application Information:
	Process ID:		0
	Application Name:	-

Network Information:
	Direction:		Inbound
	Source Address:		192.168.0.14
	Source Port:		51700
	Destination Address:	192.168.0.2
	Destination Port:		5900
	Protocol:		17

Filter Information:
	Filter Run-Time ID:	218534
	Layer Name:		ICMP Error
	Layer Run-Time ID:	28

**Comment by br6** [comment]
Its fine via SSH tunnel, but not on its own VNC RFB port.
I though it could be firewall but I disabled it. Other OSes work fine. maybe X client issues with Windows based VNC clients?

**Comment by br6** [comment]
I did some updates and its working again
[2020-07-04T12:52:24+0100] [ALPM] upgraded curl (7.71.0-1 -> 7.71.1-1)
[2020-07-04T12:52:25+0100] [ALPM] upgraded librsvg (2:2.48.7-1 -> 2:2.48.8-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded python-setuptools (1:47.3.1-1 -> 1:48.0.0-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded flatpak (1.7.2-1 -> 1.8.1-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded libappindicator-gtk3 (12.10.0-14 -> 12.10.0.r296-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded libuv (1.38.0-1 -> 1.38.1-1)
[2020-07-04T12:52:26+0100] [ALPM] upgraded tslib (1.21-2 -> 1.22-1)
[2020-07-04T12:52:29+0100] [ALPM] upgraded qt5-base (5.15.0-3 -> 5.15.0-4)

**Comment by bk138** [comment]
Great
