### ISSUE TITLE
Readme broken

### ISSUE THREAD

**Issue by Fabian42** [LibVNC/x11vnc#137]
I'm surprised that nobody seems to have noticed this in the past ~14 years, but the Readme file is totally broken. Formattings are all over the place and thousands of lines of text are simply not visible because they go over the 512K character limit (which I just today learned that it exists on Github).
I looked at the history and found changes from 2006 that already had this long Readme file. Either something about Github was different back then or it was already broken back then.

Example screenshot:
![image](https://user-images.githubusercontent.com/10481506/85990355-2c057200-b9f2-11ea-954a-9668a0357b2f.png)

How the end looks:
![image](https://user-images.githubusercontent.com/10481506/85990396-3de71500-b9f2-11ea-9440-84fa613ee0ec.png)

The file actually goes on beyond that, but it's not displayed.

**Comment by bk138** [comment]
Thanks for actually filing this ling-standing issue. PR welcome!
