### ISSUE TITLE
Mouse host mouse is drawn in wrong place when display is flipped with `-rotate`

### ISSUE THREAD

**Issue by stanford-scs** [LibVNC/x11vnc#152]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/LibVNC/x11vnc/issues/152)

If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/x11vnc

**Describe the bug**

I'm hoping to use x11vnc with a teleprompter (displaying my screen, flipped, on a tablet).  When I use the `-rotate y` option, the screen is correctly flipped so that it looks good on a mirror angled above the tablet.  Unfortunately, I can't get the host X server's cursor to display in the right location.  The shape of the cursor is rotated, but it shows at the same place as on the non-flipped screen.  In other words, when the host X server is at the top of the screen, it is also at the top of the flipped screen.

Note that on the VNC client machine, the mouse also moved backwards by default, but the `-nocursorshape` option seems to fix that problem.  However, I don't plan to provide any input from the client machine, and plan to use only the main keyboard and mouse connected to the X server.  If I'm dragging a window, it works correctly, but if I'm just trying to move the mouse, it shows up at the wrong height of the screen and so I can't see where I'm clicking.

**To Reproduce**

Run: `x11vnc -rotate y -nocursorshape`
Now using the host machine (the one running `x11vnc`, not the one running `vncviewer`) move the mouse around and try to click on something while looking at the inverted window on your VNC client.

**Expected Behavior**

When you click, the click event goes to the window under the displayed mouse, not to the window at vertical position 1080-y (if y is the current mouse position).  Moreover, when you move the host mouse up or down, you expect to see the upside-down cursor move in the opposite direction, so as to stay over the same region of the screen as in the non-flipped version.

**Screenshots**

A screen shot shows that the cursor appears to be in a different part of the screen when in fact it's near the word cursor in the xterm.
![vncmirrorbug](https://user-images.githubusercontent.com/4564109/101270060-f9427100-3729-11eb-979c-5b2b7ebef118.png)

**Desktop (please complete the following information):**
 - arch Linux recent, with x11vnc 0.9.16
 - Xorg version used: 1.20.10
 - Wayland version used: none
 

**Additional context**

Ideally it's easy to reproduce and a simple fix, but happy to provide any additional information that could be helpful.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars0.githubusercontent.com/u/4564109?v=4' alt='stanford-scs' width=24 height=24> stanford-scs](https://issuehunt.io/u/stanford-scs) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/LibVNC/x11vnc/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by darksworm** [comment]
@stanford-scs I've implemented the fix in https://github.com/LibVNC/x11vnc/pull/163.
Sadly, there's no progress for the PR and I can't foresee when or whether someone is going to approve it. 
If you'd like to use the fix earlier, i suggest you pull my fork and use that instead. https://github.com/darksworm/x11vnc

**Comment by bk138** [comment]
I've got an alternative, shorter solution in #165, please test @stanford-scs @darksworm. If that one works out over #163, I'm of course willing to split the bounty @darksworm ;-).

**Comment by darksworm** [comment]
@bk138 I'll find some time to check it out this week. I hope it works - your solution is way more elegant!

**Comment by darksworm** [comment]
> I've got an alternative, shorter solution in #165, please test @stanford-scs @darksworm. If that one works out over #163, I'm of course willing to split the bounty @darksworm ;-).

These vertical rotations do not work correctly on your branch:
- `-rotate 90y`
- `-rotate 270`
- `-rotate 90`

My best guess was that the `rotate_coords` function assumes `dxi, dyi` are already swapped when you're rotating to a vertical orientation, but oddly enough `-rotate 90x` works correctly though..

It sort-of smells like there has been a bug in `rotate_coords` which was patched externally...
