### ISSUE TITLE
x11vnc immedia

### ISSUE THREAD

**Issue by DemiMarie** [LibVNC/x11vnc#153]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/x11vnc

**Describe the bug**
x11vnc doesn’t support AF_UNIX sockets

**To Reproduce**

Start x11vnc listening on an AF_UNIX socket, or in inetd mode with an AF_UNIX socket on stdio.  Connect to the socket, and observe that x11vnc immediately exits.

**Expected Behavior**

Connections succeed

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Fedora 32
 - Xorg version used: 1.20.10
 - Wayland version used: N/A
 

**Additional context**

This is due to failing to set the TCP_NODELAY socket option.  This should not be fatal on AF_UNIX.

**Comment by bk138** [comment]
Interesting. You report that `-unixsock` options does not work? Can you please provide a command to repro? Thanks!

**Comment by DemiMarie** [comment]
`x11vnc -localhost -display :0 -unixsocket <any socket path>` should reproduce.

**Comment by bk138** [comment]
> `x11vnc -localhost -display :0 -unixsocket <any socket path>` should reproduce.

`x11vnc -localhost -display :0 -unixsock /tmp/sock` actually, yes. What's the viewer command you connect with?

Also, what x11vnc version is this happening with?

**Comment by DemiMarie** [comment]
I’m using `vncviewer` from the `tigervnc` Fedora package.  The actual socket is tunneled over SSH.

**Comment by bk138** [comment]
This is not a known bug. This means I need to reproduce your setup somehow. Please make this easy for me by providing as much info as someone familier with your setup might need.

**Comment by DemiMarie** [comment]
This turned out to be a case of user error: the `-localhost` option rejects connections on AF_UNIX sockets.
