### ISSUE TITLE
x11vnc showing double mouse cursor

### ISSUE THREAD

**Issue by navinp0304** [LibVNC/x11vnc#157]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/LibVNC/x11vnc

**Describe the bug**
 I'm trying to play a game under wine/playonlinux . Also when i play the game directly through wine  on the laptop i don't see double pointers . Only on x11vncserver and vncviewer i get this error.

So i tried few vnc server like x2go,tightvncserver and others. I was not even able to start the game. Then i tried x11vnc with options x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth /var/run/lightdm/root/:0 -usepw but in this case i couldn't   move mouse . So i did add -xkbd and -xptr to give x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth /var/run/lightdm/root/:0 -usepw **-grabkbd -grabptr -grabalways.** 
Now when i move mouse i can see there are 2 mouse pointers and i can start the game. I tried **-overlay** but it also doesn't fix the double mouse cursor.  

The top mouse pointer belongs to the game and you can click options like new game /load game etc but the below mouse pointer is confusing and when you click it on the options it does nothing.

**Expected Behavior**
There shouldn't be 2 mouse pointers.

**Screenshots**
![double_mouse](https://user-images.githubusercontent.com/74448943/105038268-1e463580-5a85-11eb-86f3-512f6e462bf5.jpg)

**Desktop (please complete the following information):**
ubuntu laptop 20.04 focal.

**Comment by bk138** [comment]
I recommend you try with another VNC server to see if the problem is specifc to x11vnc,

**Comment by navinp0304** [comment]
> I recommend you try with another VNC server to see if the problem is specific to x11vnc.

Can you recommend some of the vnc server to try ? I tried tightvncserver and x2go server both of them failed to load or start the game. It gave some errors while starting the game. Only x11vncserver could start and load the game. It is not specific to aws ec2 insance. It happens in my LAN too.

**Comment by bk138** [comment]
You might try the builtin screen sharing in GNOME (which is using the vino server).  I think you are seeing a genereal problem where the OS cursor position is not in sync wtih the program's cursor position.

**Comment by navinp0304** [comment]
Well the problem exists with GNOME(vino server) as well. It also shows 2 mouse cursors. I think if i don't open/run the game it shows only 1 mouse cursor in x11vnc server.

**Comment by bk138** [comment]
So it seems that the operating system (and thus the VNC servers) have a different understanding about cursor position than the program has. Not much we can do here.

**Comment by navinp1912** [comment]
No, I think this has to do with vnc. Without vnc I can play game fine under wine without double cursor.  I don't know if it is the protocol or implementation.

**Comment by navinp0304** [comment]
No, i think this has to do with vnc. Without vnc i can play game fine under wine without double cursor. I don't know if it is the protocol or implementation.

**Comment by navinp0304** [comment]
spice seems to work fine, no double cursor.
