### ISSUE TITLE
Ccompilation/Installation on SGI IRIX

### ISSUE THREAD

**Issue by diegocalazans** [LibVNC/x11vnc#159]
Is there a tutorial or even a pre-compiled version of the latest version for SGI IRIX

I have already made several attempts as described in the build manual on the github, but I was not successful

Thank you very much in advance

**Comment by bk138** [comment]
You can find all sorts of UNIX binaries here: https://sourceforge.net/projects/x11vnc/files/x11vnc_misc_unix_bins/0.9.13/ - Otherwise, just refer to https://github.com/LibVNC/x11vnc/blob/master/.travis.yml to see how builds are done.
