### ISSUE TITLE
Remote cursor does not move/resize any window when using multiptr

### ISSUE THREAD

**Issue by clpacheco90** [LibVNC/x11vnc#164]
**Describe the bug**
When using `multiptr` a remote cursos does not be able to move/resize any window. You can open apps, use right-click, select text and etc. But can not move any applications position

**To Reproduce**
on server side: use `x11vnc -shared -forever -multiptr`
on remote side access using tigerVNC, noVNC ...
on remote side try to click & hold a app-window and you will notice that the main-cursor change the behavior to "move-arrow" but the remote-cursor don't.
if you move on server-side the main-cursor you will notice that it moves the app-window.

**Expected Behavior**
Can be able to move and resize any app-window using `multiptr`

**Desktop (please complete the following information):**
 - OS and version:5.10.2-2-MANJARO
 - Wayland version used:mutter 3.38.2

**Comment by bk138** [comment]
Hi! That _might_ be related to the desktop, i.e. GNOME. Can you try with another desktop environment, XFCE for instance?

**Comment by clpacheco90** [comment]
Using XFCE works. Thanks!
