### ISSUE TITLE
-unixpw says not supported on Gentoo linux

### ISSUE THREAD

**Issue by pbhenson** [LibVNC/x11vnc#20]
I've always used the -unixpw option with x11vnc. At some point I upgraded and it stopped working, now it says "-unixpw is not supported on this OS/machine". I didn't have time to look at it when it first happened, and I don't recall how long ago the upgrade was, sorry. Looking at unixpw.c, this error occurs when one of LIBVNCSERVER_HAVE_FORK, LIBVNCSERVER_HAVE_SYS_WAIT_H, or LIBVNCSERVER_HAVE_WAITPID is not defined. On my system (libvncserver-0.9.10) /usr/include/rfb/rfbconfig.h doesn't seem to have LIBVNCSERVER_HAVE_WAITPID defined, although of course linux supports that call. Reviewing the source for libvncserver, I don't see that define anywhere. Why is x11vnc using it?

**Comment by bk138** [comment]
Can you check if a6852d61dce708bf5185a7e42770475a070433bc fixes this?

**Comment by pbhenson** [comment]
This fixes the issue with failing due to -unixpw not being supported, but now there is another error:

29/11/2015 21:13:07 get_pty failed.: No such file or directory

I tried setting BSD_PTY=1 to force it to use get_pty_loop and I also hacked the get_pty function to force it to use get_pty_ptmx, both resulted in this same error.

Thanks...

**Comment by bk138** [comment]
Mhh when exactly does this fail? I am getting to the builtin login screen with -unixpw at least. Debian Wheezy...

**Comment by pbhenson** [comment]
The login screen shows, but after you type in a username/password auth fails and that error shows up in the logs:

29/11/2015 21:19:28 unixpw_verify: 'henson'
29/11/2015 21:19:28 su_verify: 'henson' for login.
29/11/2015 21:19:28 unixpw_list_match: OK for 'henson'
29/11/2015 21:19:28 get_pty failed.: No such file or directory
29/11/2015 21:19:28 unixpw_verify: su_verify login for 'henson' failed.

**Comment by bk138** [comment]
phew. pls check e70123d8f778e3f0c3bf1606f68a70b0d9748c6a

**Comment by pbhenson** [comment]
Woo-hoo! That seems to have done the trick, I can successfully access vnc using -unixpw after applying these two patches.

Thanks much!
