### ISSUE TITLE
Add libv4l-dev to FAQ Q-2 Debian dependency list

### ISSUE THREAD

**Issue by mncharity** [LibVNC/x11vnc#21]
On my Ubuntu 15.10, ./configure in http://x11vnc.sourceforge.net/dev/x11vnc-0.9.14-dev.tar.gz printed
> checking linux/videodev.h usability... no
> checking linux/videodev.h presence... no
> checking for linux/videodev.h... no

I suggest adding to the FAQ Q-2 Debian dependency list at http://www.karlrunge.com/x11vnc/faq.html#faq-build this additional dependency:
> libv4l-dev  (then: sudo ln -s /usr/include/libv4l1-videodev.h /usr/include/linux/videodev.h )

Caveat: While `make` succeeds, and this recipe was multiply suggested on the web, I've not otherwise tested it.

**Comment by bk138** [comment]
Well I do not maintain the debian package. You should ask at https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=x11vnx
