### ISSUE TITLE
Debian/Ubuntu dependency for OpenGL/OpenGL.h?

### ISSUE THREAD

**Issue by mncharity** [LibVNC/x11vnc#22]
On my Ubuntu 15.10, ./configure in http://x11vnc.sourceforge.net/dev/x11vnc-0.9.14-dev.tar.gz printed
> checking OpenGL/OpenGL.h usability... no
> checking OpenGL/OpenGL.h presence... no
> checking for OpenGL/OpenGL.h... no

I failed to find an Ubuntu package which includes this file.

Perhaps, as with #21, some packaged file needs to be linked to this name, or the configure script generalized.

**Comment by bk138** [comment]
Pls report at https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=x11vnx. Thank you!
