### ISSUE TITLE
Sluggish performance and debug messages from x11vnc

### ISSUE THREAD

**Issue by jmechnich** [LibVNC/x11vnc#220]
In Debian 11 testing as well as in Debian 10 since a recent update to libvncserver, x11vnc performance is quite bad when accessing a running X session via ssh tunnel using different VNC viewers (i.e. ssvncviewer on Linux, vnc-viewer/RealVNC on macOS).

The terminal running the ssh session shows repeated output lines from x11vnc, such as:
```
The VNC desktop is:      localhost:0
*** fb_push ublen NOT ZERO: 759582801
*** fb_push ublen NOT ZERO: 759582801
(...)
```
Those messages can be triggered for example by moving the mouse around the VNC screen.

From the recent appearance of this bug in Debian 10, I was able to attribute the bug to this change in libvncserver:
https://github.com/LibVNC/libvncserver/blame/f45672cdc9b749e100be2463b1a04f3a9fc0aa26/rfb/rfb.h#L570

UPDATE_BUF_SIZE has been changed from 30000 to 32768. This macro definition is used in x11vnc as well, more specifically in [misc/turbovnc/tight.c](https://github.com/LibVNC/x11vnc/blob/master/misc/turbovnc/tight.c).

Changing the value back to 30000 and recompiling fixes the problem.

The triggered messages are printed out [here](https://github.com/LibVNC/x11vnc/blob/master/src/userinput.c#L2193).

It would be great if someone with a deeper knowledge of x11vnc and associated protocols could comment as I am not certain if things are broken here or maybe even inside the viewer code.

References:
- https://forums.debian.net/viewtopic.php?t=153655
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027043
- https://github.com/LibVNC/libvncserver/issues/521

**Comment by SunRain** [comment]
Same problem in archlinux with x11vnc 1:0.9.16.r12.g97d632c-1 built from aur

> In Debian 11 testing as well as in Debian 10 since a recent update to libvncserver, x11vnc performance is quite bad when accessing a running X session via ssh tunnel using different VNC viewers (i.e. ssvncviewer on Linux, vnc-viewer/RealVNC on macOS).
> 
> The terminal running the ssh session shows repeated output lines from x11vnc, such as:
> 
> ```
> The VNC desktop is:      localhost:0
> *** fb_push ublen NOT ZERO: 759582801
> *** fb_push ublen NOT ZERO: 759582801
> (...)
> ```
> 
> Those messages can be triggered for example by moving the mouse around the VNC screen.
> 
> From the recent appearance of this bug in Debian 10, I was able to attribute the bug to this change in libvncserver: https://github.com/LibVNC/libvncserver/blame/f45672cdc9b749e100be2463b1a04f3a9fc0aa26/rfb/rfb.h#L570
> 
> UPDATE_BUF_SIZE has been changed from 30000 to 32768. This macro definition is used in x11vnc as well, more specifically in [misc/turbovnc/tight.c](https://github.com/LibVNC/x11vnc/blob/master/misc/turbovnc/tight.c).
> 
> Changing the value back to 30000 and recompiling fixes the problem.
> 
> The triggered messages are printed out [here](https://github.com/LibVNC/x11vnc/blob/master/src/userinput.c#L2193).
> 
> It would be great if someone with a deeper knowledge of x11vnc and associated protocols could comment as I am not certain if things are broken here or maybe even inside the viewer code.
> 
> References:
> 
> * https://forums.debian.net/viewtopic.php?t=153655
> * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027043
> * [Please support larger screens libvncserver#521](https://github.com/LibVNC/libvncserver/issues/521)

Same problem in archlinux with x11vnc 1:0.9.16.r12.g97d632c-1 built from aur

**Comment by venoom27** [comment]
I am also having this issue with Arch x11vnc-1:0.9.16-5-x86_64 since I updated.

**Comment by jmechnich** [comment]
> UPDATE: This issuse (the ** fb_push ublen NOT ZERO log in systemd) appears in ArchLinux x11vnc-1:0.9.16-5-x86_64. After I update with x11vnc 1:0.9.16.r12.g97d632c-1 built from aur it dispeared.
> 
> > ...

Great to hear that. Could you investigate what fixed the problem in your case? Is there a specific patch applied to x11vnc or one of its dependencies in Arch AUR?

**Comment by venoom27** [comment]
By building the  aur version x11vnc-git 1:0.9.16.r12 it fixed the issue. Thanks

**Comment by SunRain** [comment]
Someone point out that this bug related on the libjpeg-turbo library.

**Comment by jmechnich** [comment]
Hrmm...interesting. It turns out that simply recompiling the package locally fixed the problem for me as well (on Debian 11), without removing the patch mentioned above.

I have no idea what is going on here...but it is unlikely to be an issue with the x11vnc code, so I am going to close this issue.
