### ISSUE TITLE
The option "-solid" not work in xfce4 v4.12

### ISSUE THREAD

**Issue by wtsch** [LibVNC/x11vnc#24]
Hi! 
1. This option "-solid" or "-solid xfce" or "-solid xfce:darkblue" not work in xfce4 v4.12, because xfce4 has another format for getting/setting  wallpaper style and background color style:

`xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor%s/workspace0/image-style
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor%s/workspace0/color-style`
1. This option not work in xfce4 v4.12 with in multi-monitor configuration too.
2. This option can't set the background color for the xfce4 v4.12 desktop.

See the patch in the attachment:
[dbk-xfce-solid-fix.patch.txt](https://github.com/LibVNC/x11vnc/files/320422/dbk-xfce-solid-fix.patch.txt)

Thx.

**Comment by bk138** [comment]
Hi! 
While your patch might fix this for newer XFCE versions, I think it breaks backwards compatibility? 
Also, can you provider a proper pull request?

Thanks!

**Comment by wtsch** [comment]
> While your patch might fix this for newer XFCE versions, I think it breaks backwards compatibility?
Yes. This patch is for a example. Sorry.

**Comment by bk138** [comment]
It would help if you fork and file a pull request.

**Comment by bk138** [comment]
Tentatively closing, please re-open if issue persists.
