### ISSUE TITLE
Compile error after clone

### ISSUE THREAD

**Issue by AhmedX6** [LibVNC/x11vnc#40]
Hello,

I'm on Linux.
I just want to recompile the binary "tkx11vnc".
After cloning the repo and doing "./autogen.sh", a Makefile is generated.
When I'm doing "make", after some time I got this errors :
```
/home/myhome/x11vnc/src/8to24.c:1226: undefined reference to `sraRgnDestroy'
/home/myhome/x11vnc/src/8to24.c:1292: undefined reference to `sraRgnCreateRect'
/home/myhome/x11vnc/src/8to24.c:1320: undefined reference to `sraRgnCreateRect'
/home/myhome/x11vnc/src/8to24.c:1325: undefined reference to `sraRgnSubtract'
/home/myhome/x11vnc/src/8to24.c:1327: undefined reference to `sraRgnDestroy'
/home/myhome/x11vnc/src/8to24.c:1329: undefined reference to `sraRgnEmpty'
/home/myhome/x11vnc/src/8to24.c:1334: undefined reference to `sraRgnEmpty'
/home/myhome/x11vnc/src/xinerama.c:359: undefined reference to `rfbLog'
/home/myhome/x11vnc/src/xinerama.c:369: undefined reference to `rfbLog'
/home/myhome/x11vnc/src/xinerama.c:377: undefined reference to `rfbLog'
/home/myhome/x11vnc/src/xinerama.c:378: undefined reference to `rfbLog'
```
... and many others (it's like libvncserver.so is not linked)

Can someone please help me?
Thank you !

**Comment by The-42** [comment]
Do you have libvncserver-dev[el] installed?

Could you show the log from the `./autogen.sh` step and what parameters you used?

**Comment by AhmedX6** [comment]
Hello the-42,
Thank you for your answer.

Yes the libvncserver-dev is installed.
I did not use any parameters when I ran ./autogen.sh.
I attached some screenshots you can see exactly what's happening.

Thank you

Here is after running ./autogen.sh
![screenshot from 2017-02-14 10-12-32](https://cloud.githubusercontent.com/assets/13573148/22922525/6bcdcc44-f29e-11e6-9014-2f4fd93f3e35.png)

Here is after running "make"
![screenshot from 2017-02-14 10-13-09](https://cloud.githubusercontent.com/assets/13573148/22922526/6bd47c7e-f29e-11e6-9390-df79b28a9647.png)

**Comment by The-42** [comment]
I meant the full configure log :) Especially the lines detecting libvnc libs are of interest, they should look like this:
```
checking for LIBVNCSERVER... yes
checking for LIBVNCCLIENT... yes
```
The missing symbols are from libvncserver, but having installed the development headers should have made sure the lib itself is present, too... What version are your libvnc* libraries? Are they from the repos or did you build and install them yourself? Where are libvncclient*.so and libvncserver*.so located on your system?

Last but not least: can you please recompile using `make V=1` for verbose output? The linking command (likely the last one starting with _gcc_) should look like this:
```
gcc  -g -O2   -o x11vnc x11vnc-8to24.o x11vnc-appshare.o x11vnc-avahi.o x11vnc-cleanup.o x11vnc-connections.o x11vnc-cursor.o x11vnc-gui.o x11vnc-help.o x11vnc-inet.o x11vnc-keyboard.o x11vnc-linuxfb.o x11vnc-macosx.o x11vnc-macosxCG.o x11vnc-macosxCGP.o x11vnc-macosxCGS.o x11vnc-macosx_opengl.o x11vnc-options.o x11vnc-pm.o x11vnc-pointer.o x11vnc-rates.o x11vnc-remote.o x11vnc-scan.o x11vnc-screen.o x11vnc-selection.o x11vnc-solid.o x11vnc-sslcmds.o x11vnc-sslhelper.o x11vnc-uinput.o x11vnc-unixpw.o x11vnc-user.o x11vnc-userinput.o x11vnc-util.o x11vnc-v4l.o x11vnc-win_utils.o x11vnc-x11vnc.o x11vnc-x11vnc_defs.o x11vnc-xdamage.o x11vnc-xevents.o x11vnc-xi2_devices.o x11vnc-xinerama.o x11vnc-xkb_bell.o x11vnc-xrandr.o x11vnc-xrecord.o x11vnc-xwrappers.o -lvncserver -lvncclient  -lssl -lcrypto -lcrypt -lXtst -lXtst -lXtst  -lXext -lXinerama -lXrandr -lXfixes -lXdamage -lXcomposite -lXcursor -lX11 -lXi -lcairo  -lnsl
```
X releated libs may look different, but both `-lvncserver` and `-lvncclient` should be present.

**Comment by AhmedX6** [comment]
Hello !

Yes I have this logs : 
`checking for LIBVNCSERVER... yes
 checking for LIBVNCCLIENT... yes`
I attached a file who shows this.
[logsautogen.txt](https://github.com/LibVNC/x11vnc/files/776576/logsautogen.txt)

I installed these libs with apt-get and they are installed in the path : `/usr/lib/x86_64-linux-gnu`
![screenshot from 2017-02-15 10-39-58](https://cloud.githubusercontent.com/assets/13573148/22968594/3df41af8-f36b-11e6-8df3-51aa369cdb75.png)

But I also found other libvnc files install in the path : `/usr/local/lib`
![screenshot from 2017-02-15 10-42-18](https://cloud.githubusercontent.com/assets/13573148/22968655/8d6ea8f0-f36b-11e6-88f7-d03bed35f787.png)

Here are the verbose output file (.txt) as you can see it links correctly -lvncserver but still I have errors.
[verboseoutput.txt](https://github.com/LibVNC/x11vnc/files/776607/verboseoutput.txt)

**Comment by The-42** [comment]
Yes, `-lvncserver` gets linked, but look at which one is linked:
```gcc [...] -L/usr/local/lib -lvncserver -L/usr/local/lib -lvncclient [...]```
You're linking the ones from `/usr/local/lib` and not your system libs :)

I suspect the local versions must have been built and installed from source at some point, but they seem to be outdated or broken and don't match the headers from `libvncserver-dev` anymore. I suggest getting rid of your local libs as it is a bad idea to have both local and system libraries of the same software and SO version (but not release version) installed. You might as well have successfully linked against one and loaded the other when running the binary, and that's when debugging really gets fun ;)
As an alternative you might want to set the `LIBVNCSERVER_LIBS` and `LIBVNCCLIENT_LIBS` configure variables to get rid of those link path flags, but I really advise solving this problem more permanently by cleansing your `usr/local/lib`.

**Comment by AhmedX6** [comment]
Hello the-42 !

Problem solved ! Thank you so much !
I just copy/paste the libvncserver files contained in /usr/lib/x86_64-linux-gnu in /usr/local/lib and the compilation works =)

Thank you again ! :+1:

**Comment by The-42** [comment]
Deleting the libs from `/usr/local/lib` instead of replacing them should have been enough, but if things work for you now, great!

Can you please close this issue then? :)
