### ISSUE TITLE
Cursor is blocked when using -multipr

### ISSUE THREAD

**Issue by lucasmouilleron** [LibVNC/x11vnc#51]
When running x11vnc with -multiptr (and -noxfixes as advised by the startup doc), the cursor is blocked in the middle of the screen from all my viewers (Screens4, MacOS Screensharing).

x11vnc was installed with this : 
apt-get install -y libxtst-dev libssl-dev libjpeg-dev xorg-dev libxi-dev libvncserver-dev checkinstall autoconf
cd /tmp && wget https://github.com/LibVNC/x11vnc/archive/master.zip;unzip master.zip;cd x11vnc-master && autoreconf --install && ./configure && make && make install

**Comment by bk138** [comment]
Can you pls try with some other viewers?

What is the result with Linux viewers? (I assume you're running some Debian derivative on the server box...)
