### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [LibVNC/x11vnc#63]
Based on https://repology.org/metapackage/x11vnc/versions it's unclear to me whether we should treat 0.9.13 or 0.9.14 or something else as the current stable version in Homebrew.

**Comment by bk138** [comment]
It's 0.9.14 https://github.com/LibVNC/x11vnc/releases with 0.9.15 upcoming (https://github.com/LibVNC/x11vnc/milestone/2).

**Comment by ilovezfs** [comment]
Thanks @bk138! Any idea why http://www.karlrunge.com/x11vnc/ still says 0.9.13?

**Comment by bk138** [comment]
@ilovezfs pls see the edit of my answer above. We (mostly me) took the x11vnc codebase that resided in the libvncserver repo, moved the x11vnc code to its own repo here and continued developement as Karl could not be reached.

**Comment by ilovezfs** [comment]
Ah, OK.

**Comment by bk138** [comment]
Here's the mail about the splitting-off of x11vnc code: https://sourceforge.net/p/libvncserver/mailman/message/32196002/

**Comment by bk138** [comment]
Last message from Karl _seems_ to be https://sourceforge.net/p/libvncserver/mailman/message/26831074/
