### ISSUE TITLE
-unixpw doesn't seem to work, OpenSUSE 42.3

### ISSUE THREAD

**Issue by batagy** [LibVNC/x11vnc#66]
Dear x11vnc team!

I'm a long time x11vnc user. I'm observing an issue.

I compiled x11vnc 0.9.15 lastmod: 2018-02-04 version successfully, on OpenSUSE 42.3.
I'm trying to use x11vnc in a systemd service, it would run with below options:

/etc/systemd/system/x11vnc.socket
```
[Unit]
Description=x11vnc Socket for Per-Connection Servers

[Socket]
ListenStream=5900
Accept=yes

[Install]
WantedBy=sockets.target
```

/etc/systemd/system/x11vnc@.service
```
[Unit]
Description=x11vnc Systemd Service Component
After=network.target
Requires=x11vnc.socket

[Service]
EnvironmentFile=-/etc/sysconfig/x11vnc_config
Type=simple
ExecStart=-/usr/local/bin/x11vnc $X11VNC_ARGUMENTS
ExecReload=-/usr/local/bin/x11vnc $X11VNC_ARGUMENTS
RemainAfterExit=yes
StandardInput=socket
StandardOutput=inherit

[Install]
WantedBy=multi-user.target
Also=x11vnc.socket
```

/etc/sysconfig/x11vnc_config
```
UNIXPW_DISABLE_LOCALHOST=1
UNIXPW_DISABLE_SSL=1
FD_SESS=xfce
X11VNC_CREATE_GEOM=1600x950
FD_USERPREFS=x11vnc_create
X11VNC_ARGUMENTS="-inetd -unixpw -users unixpw= -xdummy -o /var/log/x11vnc.log -sloppy_keys -clear_keys -skip_lockkeys -repeat"
```

Please note that I'm not fully sure if systemd is configured properly, but it seems to work.
Also please note that above is sending is cleartext, and its not recommended in normal cases. Anyway I get the same issue also with SSL.

Service is started:
systemctl daemon-reload
systemctl status x11vnc.socket
systemctl start x11vnc.socket

Now, after connecting with a VNC viewer (TigerVNC), the '-unixpw' authentication getting failed always.
I'm no sure if some configuration is missing or this is an issue in x11vnc.

x11vnc log:

> 09/03/2018 14:55:24 Skipping -ssl/-stunnel requirement due to
09/03/2018 14:55:24 UNIXPW_DISABLE_SSL setting.
09/03/2018 14:55:24
09/03/2018 14:55:24 x11vnc version: 0.9.15 lastmod: 2018-02-04  pid: 4094
09/03/2018 14:55:24 Enabling -xrandr for possible use of Xdummy server.
09/03/2018 14:55:24
09/03/2018 14:55:24 wait_for_client: WAIT:cmd=FINDCREATEDISPLAY-Xdummy
09/03/2018 14:55:24
09/03/2018 14:55:24 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/2560
09/03/2018 14:55:24
09/03/2018 14:55:24   other clients:
09/03/2018 14:55:24 Normal socket connection
09/03/2018 14:55:24 incr accepted_client=1 for ::ffff:10.0.2.2:49557  sock=3
09/03/2018 14:55:24 new client: ::ffff:10.0.2.2 in non-unixpw_in_rfbPE.
09/03/2018 14:55:24 rfbPE: got new client in non-rfbPE
09/03/2018 14:55:24 wait_for_client: got client
09/03/2018 14:55:24 taking unixpw_client off hold.
09/03/2018 14:55:24 Client Protocol Version 3.8
09/03/2018 14:55:24 Protocol version sent 3.8, using 3.8
09/03/2018 14:55:24 rfbProcessClientSecurityType: executing handler for type 1
09/03/2018 14:55:24 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
09/03/2018 14:55:24 Pixel format for client ::ffff:10.0.2.2:
09/03/2018 14:55:24   32 bpp, depth 24, little endian
09/03/2018 14:55:24   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
09/03/2018 14:55:24 no translation needed
09/03/2018 14:55:24 Enabling X-style cursor updates for client ::ffff:10.0.2.2
09/03/2018 14:55:24 Enabling full-color cursor updates for client ::ffff:10.0.2.2
09/03/2018 14:55:24 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
09/03/2018 14:55:24 Enabling NewFBSize protocol extension for client ::ffff:10.0.2.2
09/03/2018 14:55:24 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
09/03/2018 14:55:24 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECD)
09/03/2018 14:55:24 Enabling LastRect protocol extension for client ::ffff:10.0.2.2
09/03/2018 14:55:24 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC7)
09/03/2018 14:55:24 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC8)
09/03/2018 14:55:24 Using image quality level 8 for client ::ffff:10.0.2.2
09/03/2018 14:55:24 Using JPEG subsampling 0, Q92 for client ::ffff:10.0.2.2
09/03/2018 14:55:24 Using tight encoding for client ::ffff:10.0.2.2
09/03/2018 14:55:28 unixpw_verify: 'user'
09/03/2018 14:55:28 su_verify: 'user' for login.
09/03/2018 14:55:28 unixpw_verify: su_verify login for 'user' failed.
09/03/2018 14:55:32 unixpw_verify: 'user'
09/03/2018 14:55:32 su_verify: 'user' for login.
09/03/2018 14:55:32 unixpw_verify: su_verify login for 'user' failed.
09/03/2018 14:55:35 rfbProcessClientNormalMessage: read: Connection reset by peer
09/03/2018 14:55:35 client_count: 0
09/03/2018 14:55:35 inetd viewer exited.

> 

OS is OpenSUSE 42.3, 64bit.
Kernel version: 4.4.114-42-default

Could you check this? How can I troubleshoot it?
Thanks in advance

**Comment by bk138** [comment]
Hi!
Can you please
* check if that happens with 0.9.13 or 0.9.14 as well? I remember there was a regression (#20 and, related #37) but this is fixed since then.
* check if the issue pops up with 0.9.15 _without_ systemd?

**Comment by batagy** [comment]
Hi!

Thanks for your help!
Yes, now I checked these questions.

1) 0.9.15 without systemd:
Same issue, -unixpw fails to authenticate.
(same arguments as for systemd, but no -inetd)

2) 0.9.13 (Karl Runge last release).
Compiled successfully, -unixpw successful, it authenticates.

> 10/03/2018 10:29:25 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 7933
> 10/03/2018 10:29:25 Enabling -xrandr for possible use of Xdummy server.
> ...
> 10/03/2018 10:29:41 Using tight encoding for client 192.168.56.1
> 10/03/2018 10:29:45 unixpw_verify: 'user'
> 10/03/2018 10:29:45 su_verify: 'user' for login.
> 10/03/2018 10:29:46 unixpw_verify: su_verify login for 'user' succeeded.
> 10/03/2018 10:29:46 apply_opts: set unixname to: user
> 10/03/2018 10:29:46 could not read user prefs /home/user/x11vnc_create
> 10/03/2018 10:29:46 fopen: No such file or directory
> 10/03/2018 10:29:46 wait_for_client: unixpw finished.
> 10/03/2018 10:29:46 client useCopyRect: 192.168.56.1 -1
> 10/03/2018 10:29:46 client_set_net: 192.168.56.1  0.0007
> 10/03/2018 10:29:46 wait_for_client: running: env X11VNC_SKIP_DISPLAY=''  /bin/sh /tmp/x11vnc-find_display.AArrLQ
> 10/03/2018 10:29:46 su_verify: 'user' for command.
> 10/03/2018 10:29:46 wait_for_client: find display cmd failed.
> 10/03/2018 10:29:46 wait_for_client: running: env USER='user' FD_GEOM='' FD_SESS='xfce' FD_OPTS='' FD_EXTRA='' FD_PROG='' FD_XSRV='' FD_CUPS='' FD_ESD='' FD_NAS='' FD_SMB='' FD_TAG='' FD_XDMCP_IF='' FD_XDUMMY_RUN_AS_ROOT=''  /bin/sh /tmp/x11vnc-find_display.AArrLQ Xdummy
> trying N=20 ...
> /usr/bin/xauth: (argv):1:  bad display name "virtsuse.suse:20" in "add" command
> redir_daemon=
> /usr/bin/xauth: (argv):1:  bad display name "virtsuse.suse:20" in "nextract" command
> No matches found, authority file "-" not written

3) 0.9.14 (1st Community release version)
This is not compiling for me. Maybe I don't do properly.

> virtsuse:/x11vnc-0.9.14 # ./prepare_x11vnc_dist.sh
> cp: cannot stat 'x11vnc/README': No such file or directory
> cp: cannot stat 'x11vnc/RELEASE-NOTES': No such file or directory
> cat: LibVNCServer.spec.in: No such file or directory
> mv: cannot stat 'libvncserver/Makefile.am': No such file or directory
> ./prepare_x11vnc_dist.sh: line 92: libvncserver/Makefile.am: No such file or directory
> cat: libvncserver/Makefile.am.LibVNCServer: No such file or directory
> mv: cannot stat 'libvncclient/Makefile.am': No such file or directory
> ./prepare_x11vnc_dist.sh: line 101: libvncclient/Makefile.am: No such file or directory
> cat: libvncclient/Makefile.am.LibVNCServer: No such file or directory
> mv: cannot stat 'x11vnc/Makefile.am': No such file or directory
> ./prepare_x11vnc_dist.sh: line 110: x11vnc/Makefile.am: No such file or directory
> cat: x11vnc/Makefile.am.LibVNCServer: No such file or directory
> cp: cannot stat 'classes/Makefile.am': No such file or directory
> ./prepare_x11vnc_dist.sh: line 117: classes/Makefile.am: No such file or directory
> ./prepare_x11vnc_dist.sh: line 118: classes/Makefile.am: No such file or directory
> cp: cannot stat 'classes/ssl/Makefile.am': No such file or directory
> ./prepare_x11vnc_dist.sh: line 121: classes/ssl/Makefile.am: No such file or directory
> ./prepare_x11vnc_dist.sh: line 123: classes/ssl/Makefile.am: No such file or directory
> ./prepare_x11vnc_dist.sh: line 124: classes/ssl/Makefile.am: No such file or directory
> ./prepare_x11vnc_dist.sh: line 125: classes/ssl/Makefile.am: No such file or directory
> chmod: cannot access 'classes/ssl/ss_vncviewer': No such file or directory
> make: *** No rule to make target 'x11vnc-0.9.13.tar.gz'.  Stop.
> mv: cannot stat 'x11vnc/Makefile.am.LibVNCServer': No such file or directory
> mv: cannot stat 'libvncserver/Makefile.am.LibVNCServer': No such file or directory
> mv: cannot stat 'libvncclient/Makefile.am.LibVNCServer': No such file or directory
> mv: cannot stat 'classes/Makefile.am.LibVNCServer': No such file or directory
> mv: cannot stat 'classes/ssl/Makefile.am.LibVNCServer': No such file or directory
> virtsuse:~/x11vnc-0.9.14 #

4) 0.9.14 beta (beta from Karl Runge in 2014!)
This compiles successfully. -unixpw successful, it authenticates.

> 10/03/2018 10:44:08 x11vnc version: 0.9.14 lastmod: 2013-11-21  pid: 15505
> 10/03/2018 10:44:08 Enabling -xrandr for possible use of Xdummy server.

There is actually also another issue that x11vnc doesn't find an already existing display with my usage, and doesn't attach for it. This second issue is present also with old 0.9.13 version. That issue was not present on OpenSUSE 13.1, but appeared with OpenSUSE 13.2. But this is a separate thing. Let's not mix it. I'll open another ticket for this one later, if we solve -unixpw.

Thanks in advance.
Let me know if can help further with logs.

**Comment by bk138** [comment]
OK, let's concentrate on the 0.9.15 build log. Can youn post `config.log` after running `./autogen.sh`, please?

**Comment by batagy** [comment]
[config-0.9.15.log](https://github.com/LibVNC/x11vnc/files/1799475/config-0.9.15.log)

Hi! Please find config.log attached. This for 0.9.15 after `./autogen.sh`.
If `./autogen.sh` is used, `./configure` command is not needed then?

**Comment by bk138** [comment]
it basically is `autoreconf -fi; ./configure`, yes

**Comment by batagy** [comment]
Hi bk138,

Do you find anything interesting in the log I've attacted, for my issue?

Thanks in advance

**Comment by batagy** [comment]
Hi bk138,

I'm still looking for the answer and solution for this ticket. Could you check please?

Thanks

**Comment by batagy** [comment]
Hi!

Is there any possibility to check my build log about my problem?

Thanks

**Comment by batagy** [comment]
Hi Christian,

Could you still check my log, if you have a bit time?
Original problem: -unixpw doesn't seem to work.

Thanks in advance
György

**Comment by bk138** [comment]
Hi György,
I finally found some time to check this out. Basically it is: worksforme with current master ca65a1c7e1b2e6e0049078280dae347e0f0c5ea0. 

For testing, I used this script:
```
#!/bin/sh
UNIXPW_DISABLE_SSL=1
src/x11vnc -unixpw -users unixpw= -xdummy
```
Started from a shell. This  allows me to login (or pass the login as it fails to find a session afterwards, but this is just a test...)  as a different user than the one currently logged in. The same one is _not_ working.

**Comment by bk138** [comment]
You might also want to take a look at bd8f7ccb3f8566e7127a569972bfc5eb276f900a, I spotted a few more build system corner cases.

**Comment by batagy** [comment]
Hi Christian,

I'm sorry for late answer, I was on vacation.
Thanks really for checking it!

I'm although no clear with understanding your answer. Do you mean you fixed something, and I should try to re-build from latest code?

György

**Comment by bk138** [comment]
Hi Güörgy,
yes and yes, although it's not much I changed

**Comment by bk138** [comment]
good to hear! and thanks for discovering this!
