### ISSUE TITLE
Wrong preprocessor definitions at src/linuxfb.c

### ISSUE THREAD

**Issue by yeyo** [LibVNC/x11vnc#68]
Please replace LIBVNCSERVER_HAVE_SYS_IOCTL_H with HAVE_SYS_IOCTL_H - This change allow to run "-rawfb console"

**Comment by bk138** [comment]
Care to file a pull request?

**Comment by bk138** [comment]
Closed via 1ae1ef1ca6173081913325a682fac4cca1a61321.
