### ISSUE TITLE
Existing display not found when running as service, OpenSUSE 42.3

### ISSUE THREAD

**Issue by batagy** [LibVNC/x11vnc#74]
Dear x11vnc team!

I'm using latest x11vnc 0.9.15 , master code taken on 2018-07-24.
OpenSUSE 42.3. It's running as systemd service.

Basicly this arguments used:
```
UNIXPW_DISABLE_SSL=1
x11vnc -inetd -unixpw -users unixpw= -xdummy -o /var/log/x11vnc.log -sloppy_keys -clear_keys -skip_lockkeys -repeat
```

Problem: an existing running Xdummy display is not found by x11vnc. The service is creating a new display again, even if one was already created and running.

The issue is not a new, problem is already present in x11vnc 0.9.13.
It worked with OpenSUSE 13.1, but issue since OpenSUSE 13.2.

Reproduction steps:
----------
1. Login with a user

> virtsuse:~ # ps -ef | grep dummy
> username   4285     1  2 13:34 ?        00:00:00 /usr/local/bin/x11vnc -inetd -unixpw -users unixpw= -xdummy -o /var/log/x11vnc.log -sloppy_keys -clear_keys -skip_lockkeys -repeat
> root      4870     1  0 13:34 ?        00:00:00 /usr/bin/xinit /bin/su - username -c /tmp/.cd450914215.N1gzCg -- /usr/local/bin/Xdummy :20 -geometry 1600x950 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G
> root      4877  4870  2 13:34 ?        00:00:00 Xorg :20 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G -config xdummy_modified_xconfig.conf_20 vt17
> root      5174  1656  0 13:35 pts/1    00:00:00 grep --color=auto dummy
> virtsuse:~ #

2. Check display

> username@virtsuse:/Desktop> echo $DISPLAY 
> :20.0
> username@virtsuse:/Desktop> 

3. Close VNC window

> virtsuse:~ # ps -ef | grep dummy
> root      4870     1  0 13:34 ?        00:00:00 /usr/bin/xinit /bin/su - username -c /tmp/.cd450914215.N1gzCg -- /usr/local/bin/Xdummy :20 -geometry 1600x950 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G
> root      4877  4870  5 13:34 ?        00:00:03 Xorg :20 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G -config xdummy_modified_xconfig.conf_20 vt17
> root      5208  1656  0 13:36 pts/1    00:00:00 grep --color=auto dummy
> virtsuse:~ #
> 

4. Login with same user again

> virtsuse:~ # ps -ef | grep dummy
> root      4870     1  0 13:34 ?        00:00:00 /usr/bin/xinit /bin/su - username -c /tmp/.cd450914215.N1gzCg -- /usr/local/bin/Xdummy :20 -geometry 1600x950 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G
> root      4877  4870  3 13:34 ?        00:00:03 Xorg :20 -depth 24 -nolisten tcp -auth /tmp/.xas450925628.YZLE0G -config xdummy_modified_xconfig.conf_20 vt17
> username   5210     1  2 13:36 ?        00:00:00 /usr/local/bin/x11vnc -inetd -unixpw -users unixpw= -xdummy -o /var/log/x11vnc.log -sloppy_keys -clear_keys -skip_lockkeys -repeat
> root      5770     1  0 13:36 ?        00:00:00 /usr/bin/xinit /bin/su - username -c /tmp/.cd542521118.gITjWa -- /usr/local/bin/Xdummy :21 -geometry 1600x950 -depth 24 -nolisten tcp -auth /tmp/.xas54253340.BlbcWf
> root      5775  5770  5 13:36 ?        00:00:00 Xorg :21 -depth 24 -nolisten tcp -auth /tmp/.xas54253340.BlbcWf -config xdummy_modified_xconfig.conf_21 vt17
> root      6050  1656  0 13:36 pts/1    00:00:00 grep --color=auto dummy
> virtsuse:~ #
> 

5. Check display

> username@virtsuse:/Desktop> echo $DISPLAY 
> :21.0
> username@virtsuse:/Desktop> 
> 

Could you check this? How can I troubleshoot it?
Thanks in advance

**Comment by batagy** [comment]
Hi Christian, Do you have idea, how can I check? Thanks, György

**Comment by bk138** [comment]
Not really, sorry.

**Comment by batagy** [comment]
Hi Christian, Ok, I understand.

But, is there some debug mode in x11vnc to get a bit more information? The problematic message is below in x11vnc.log:

> wait_for_client: find display cmd failed
I'd like to get some more detail what exactly happens in this step. How x11vnc is trying to authenticate, what commands are used? If I'd know what's failing, maybe I could go forward.

Thanks
György

**Comment by bk138** [comment]
I would go looking for that message in the code and do printf debugging.

**Comment by batagy** [comment]
Hi! Do you mean, I should do that printf debugging, or can you help? Thanks.

**Comment by batagy** [comment]
Ok. Thanks anyway. We can close this.
