### ISSUE TITLE
disable extra monitors

### ISSUE THREAD

**Issue by megamaced** [LibVNC/x11vnc#76]
Hi,

Is it possible to configure x11vnc to disable any monitor that isn't the primary? This is to avoid having to scroll through 3 different screens. If the monitors were disabled, all the windows will move to the primary monitor

**Comment by bk138** [comment]
Yes, I think so.

**Comment by megamaced** [comment]
Great would love to know how! I found the -noxinerama option and that does only serve the primary screen to the VNC client, but the other screens are still on the physical monitors so applications placed on those cant be seen through VNC

**Comment by bk138** [comment]
So you want some screens not served via VNC or disabled in the sense of powered off?

**Comment by megamaced** [comment]
I wanted the secondary screens disabled so that my VNC client is served only 1 screen but also all of my applications from the other screens get moved over to the primary screen. 

I also wanted dpms so that the physical primary screen is off

My client is Microsoft Remote Desktop client and x11vnc is proxied via XRDP.

I have it working now, I put a solution together using the -afteraccept and -gone options in x11vnc, and I use those to call xrandr

`/usr/bin/x11vnc -find -auth /var/run/gdm/$(ls /var/run/gdm | grep $(whoami))/database -once -loop --forcedpms -noxinerama -nopw -localhost -no6 -geometry 1920x1200 -xrandr resize -afteraccept "xrandr --output DP-5 --off && xrandr --output DP-6 --off" -gone "xrandr --output DP-5 --right-of DP-4 --auto && xrandr --output DP-6 --right-of DP-5 --auto && loginctl lock-session"`
