### ISSUE TITLE
No unicode support for clipboard

### ISSUE THREAD

**Issue by andoruB** [LibVNC/x11vnc#77]
OS: Arch Linux (Server) / Debian Sid (Client)
x11vnc version: 0.9.15
VNC client: Vinagre 3.22.0

When I try to do a copy/paste from the client to the server, and the string that's in the clipboard has CJK/Unicode characters, it translates to question marks on the server for some reason. Not sure if there's something misconfigured, or if I did something wrong, but I did read the manpage for x11vnc, and there aren't specific switches for this problem, so I'll assume this hasn't been implemented yet, or Vinagre is the culprit.

Here's the command line with which I start x11vnc: 

``$ x11vnc -many -allow 192.168.1. -nodragging``

**Comment by bk138** [comment]
No, that's in RFB, the underlying network protocol: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#clientcuttext
Unless someone implements https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extended-clipboard-pseudo-encoding in LibVNCServer and LibVNCClient, we are limited to Latin-1 charset.

**Comment by andoruB** [comment]
Thanks for explaining!
