### ISSUE TITLE
-bg or -loopbg options no longer work

### ISSUE THREAD

**Issue by gsra99** [LibVNC/x11vnc#9]
x11vnc no longer goes into the background upon starting

**Comment by bk138** [comment]
Version?

**Comment by gsra99** [comment]
I think it is the last updated version on 11 Jan 2015. It was working fine on version 0.9.13, but not on the update. I apologise, but I cannot specifiy the exact version as I use gentoo linux. I was using version 0.9.13 and in the latest portage updates it install 0.9.13_p20150111, which I am assuming is the last update on 11 Jan 2015.

**Comment by bk138** [comment]
FYI, 59e6916c7a5c22ae87508163eb83b2f33602d497 also shows the issue.

**Comment by bk138** [comment]
K, found it. Fixed in master. That was quick ;-)

**Comment by gsra99** [comment]
Just compiled the git version -bg now works, but -loopbg causes x11vnc to keep crashing and restarting as far as I can see.
