### ISSUE TITLE
max clients limited to 7 when multipointer active

### ISSUE THREAD

**Issue by dmanye** [LibVNC/x11vnc#97]
hello,
i need to setup the server with ~20 simultaneous clients in readonly mode. to see the pointer in client windows, i activate de -multipointer option but, in this case, only seven clients are allowed at the same time. if i don't use the multupointer option i can reach 8 or more clients. 
am i doing some thing wrong? is there any way to have 20 clients and see the pointer in the client?
i'm using the remmina client.
thanks.

**Comment by bk138** [comment]
Hi,
I reckon you are reffering to `-multiptr`? Please read the friendly manual.and watch out for `-shared`, `-viewonly` and `-cursor`.

**Comment by bk138** [comment]
I recommand `x11vnc -shared -viewonly -nocursorshape`. You'll probably have to play around a bit with the multiple options:

**Comment by dmanye** [comment]
it works! thank you very much!
